### ISSUE TITLE
How to specify nbest list in trans format?

### ISSUE THREAD

**Issue by raingo** [snover/terp#1]
I would like to use TERP as easy as possible, so I tried the trans format, but seems like there are bugs relating to nbest hypothesis.

I modified the test/sample.*.sgm files to the following two files (in the end), and run 

```
./bin/terpa -h test/sample.hyp.trans -r test/sample.ref.trans
```

but there are warnings and exceptions. Could you please help? 

After I add a `continue` after the line https://github.com/snover/terp/blob/master/src/com/bbn/mt/terp/TERplus.java#L239, the exception gone, but I don't know if that's the right way to fix it.

```
"test/sample.hyp.trans" was successfully parsed as Trans text
"test/sample.ref.trans" was successfully parsed as Trans text
Creating Segment Phrase Tables From DB
[][1][1]
Processing [1][1]
WARNING: Blank or empty hypothesis for segment: [1][1]
Processing [1][1]:01
Processing [1][1]:02
Processing [1][1]:03
Finished Calculating TERp
Exception in thread "main" java.lang.NullPointerException
    at com.bbn.mt.terp.TERalignment.getAlignDetail(TERalignment.java:223)
    at com.bbn.mt.terp.TERoutput.output_align(TERoutput.java:416)
    at com.bbn.mt.terp.TERoutput.output_align(TERoutput.java:102)
    at com.bbn.mt.terp.TERoutput.output(TERoutput.java:79)
    at com.bbn.mt.terp.TERoutput.output(TERoutput.java:61)
    at com.bbn.mt.terp.TERplus.run(TERplus.java:282)
    at com.bbn.mt.terp.TERplus.run(TERplus.java:91)
    at com.bbn.mt.terp.TERplus.main(TERplus.java:56)
```

The testing files:

sample.hyp.trans

```
The Prague stock exchange at the end of the day ([1][1]:1)
After the sharp fall in the morning, the Prague Stock Exchange correct its losses. ([1][1]:2)
The transactions with shares of ez reached almost half of the normal daily day. ([1][1]:3)
```

sample.ref.trans

```
Prague Stock Market falls to minus by the end of the trading day ([1][1])
After a sharp drop in the morning, the Prague Stock Market corrected its losses. ([1][1])
Transactions with stocks from the Czech Energy Enterprise (EZ) reached nearly half of the regular daily trading. ([1][1])
The Prague Stock Market immediately continued its fall from Monday at the beginning of Tuesday's trading, when it dropped by nearly six percent. ([1][1])
This time the fall in stocks on Wall Street is responsible for the drop. ([1][1])
The reaction of the market to the results of the vote in the American House of Representatives, which refused to support the plan for the stabilization of the financial sector there, has manifested itself here as well. ([1][1])
Congress yields: US government can pump 700 billion dollars into banks ([1][1])
The top representatives of the American Congress and George W. Bush's cabinet have agreed upon a broader form of the agreement on ([1][1])
financial assistance for the American financial system. ([1][1])
The vote on it will take place at the beginning of next week. ([1][1])
```

**Comment by rsanjaykamath** [comment]
I got the output correctly.

Two fixes in your file: 

- Your hypothesis file has ([1][1]:1) as suffix, it should be in the format of ([1][1][1])

- Number of references and number of hypothesis should be the same.

It works well for me.

sample.hyp.trans

> The Prague stock exchange at the end of the day ([1][1][1])
After the sharp fall in the morning, the Prague Stock Exchange correct its losses. ([1][1][2])
The transactions with shares of ez reached almost half of the normal daily day. ([1][1][3])


sample.ref.trans

> Prague Stock Market falls to minus by the end of the trading day ([1][1][1])
After a sharp drop in the morning, the Prague Stock Market corrected its losses. ([1][1][2])
Transactions with stocks from the Czech Energy Enterprise (EZ) reached nearly half of the regular daily trading. ([1][1][3])

 
output: 

> ./bin/terpa -h test/sample.hyp.sgm -r test/sample.ref.sgm
 Loading parameters from .//data/terpa.param
Loading parameters from .//data/data_loc.param
"test/sample.hyp.sgm" was successfully parsed as Trans text
"test/sample.ref.sgm" was successfully parsed as Trans text
Creating Segment Phrase Tables From DB
Processing [1][1][1]
Processing [1][1][2]
Processing [1][1][3]
Finished Calculating TERp
Total TER: 0.45 (22.15 / 49.00)

**Comment by desilinguist** [comment]
Thanks @rsanjaykamath! I'm going to close this issue for now.
