### ISSUE TITLE
The Html output format - obsolete link to CSS

### ISSUE THREAD

**Issue by tofula** [snover/terp#2]
Hello,

thanks for the TERP. I would like to use the html output format. Unfortunately it looks like the css sheet is not available anymore on the URL specified in the html: http://www.umiacs.umd.edu/~snover/terp/terp_style.css

See the  output_html function inside  :https://github.com/snover/terp/blob/master/src/com/bbn/mt/terp/TERoutput.java.
I guess it would be best to simply add the css into source.

Thank you,
Tomas

**Comment by desilinguist** [comment]
@snover do you have the CSS lying around somewhere?

**Comment by tofula** [comment]
Hi team, is there any news about the css? Thanks.

**Comment by snover** [comment]
Unfortunately, I haven't been able to find the old .css file that TERp
used.  Looks like it was gobbled up by the old webserver.

**Comment by tofula** [comment]
I see, such things happen sometimes. Thanks for our effort.

**Comment by desilinguist** [comment]
@tofula we have restored the CSS file to a new location. Can you please try out the PR #3  and see if that works for you. Once it does, we can merge it in. Thanks!

**Comment by tofula** [comment]
Great, I can confirm the css is now found and rendered correctly. Thanks for the fix!

Note - I would also suggest adding the output encoding to the Html page as well.
