### ISSUE TITLE
Not able to use trans format

### ISSUE THREAD

**Issue by Pinkertoncito** [snover/terp#4]
Hi, I try to use the trans format.  At first I didn't understand what that was because I wasn't able to parse normal text.  Anyway, I have two small files, foo and bar:

$ cat foo
i am nice
i am good
i am bad
$ cat bar
i am nice
i am good
i am wild

I try the following basic usage:
$ bin/terp -r foo -h bar
Warning, Invalid line: i am nice
Warning, Invalid line: i am good
Warning, Invalid line: i am wild
"bar" was successfully parsed as Trans text
Warning, Invalid line: i am nice
Warning, Invalid line: i am good
Warning, Invalid line: i am bad
"foo" was successfully parsed as Trans text
Creating Segment Phrase Tables From DB
Finished Calculating TERp
Total TER: NaN (0,00 / 0,00)

and get no result.  It reports that the lines are not valid, and I have no idea why.  I have tried to look for things in the documentation, such as options needed for the trans format or additional constraints on the text, but wasn't able to find anything.

The sample files work, so I think the installation is ok:

$ bin/terp -r test/sample.ref.sgm -h test/sample.hyp.sgm 
"test/sample.hyp.sgm" was successfully parsed as XML
"test/sample.ref.sgm" was successfully parsed as XML
Creating Segment Phrase Tables From DB
Processing [ihned.cz/2008/09/29/36559][0001]
Processing [ihned.cz/2008/09/29/36559][0002]
Processing [ihned.cz/2008/09/29/36559][0003]
Processing [ihned.cz/2008/09/30/36776][0001]
Processing [ihned.cz/2008/09/30/36776][0002]
Processing [ihned.cz/2008/09/30/36776][0003]
Processing [ihned.cz/2008/09/30/36776][0004]
Processing [ihned.cz/2008/09/30/36776][0005]
Processing [ihned.cz/2008/09/30/36776][0006]
Finished Calculating TERp
Total TER: 0,53 (90,00 / 171,00)

**Comment by desilinguist** [comment]
The TRANS format is developed specifically for translation systems and requires that the hypothesis and the reference files have one segment/sentence per line but ALSO that each line should have an id following it after a space and in parentheses. These IDs generally take the form of `[SYSTEM_NAME][DOCUMENT_ID][SEGMENT_NUMBER]`.

So, if you rename your files to `foo.trans` and `bar.trans` (you need the extensions) and change them to look like the following such that each corresponding line has a matching ID of the required form:

``` bash
$> cat foo.trans
i am nice ([sys][doc][1])
i am good ([sys][doc][2])
i am bad ([sys][doc][3])

$> cat bar.trans
i am nice ([sys][doc][1])
i am good ([sys][doc][2])
i am wild ([sys][doc][3])
```

TERp will run just fine:

``` bash
$> bin/terp -r foo.trans -h bar.trans
"/tmp/bar.trans" was successfully parsed as Trans text
"/tmp/foo.trans" was successfully parsed as Trans text
Creating Segment Phrase Tables From DB
Processing [sys][doc][1]
Processing [sys][doc][2]
Processing [sys][doc][3]
Finished Calculating TERp
Total TER: 0.11 (1.00 / 9.00)
```

I will update the README to document the TRANS format explicitly.
